[tool.poetry]
name = "Gilded rose"
version = "0.1.0"
description = "Gilded rose kata"
authors = ["Zeger Hendrikse <zegerh@yahoo.co.uk>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10.0,<3.13"
mamba = "^0.11.2"
expects = "^0.9.0"
pytest-cov = "^5.0.0"
coverage = "^7.5.4"
approvaltests = "^14.0.0"
pytest-watch = "^4.2.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
